export const LINK_VOTE_UP="LINK_VOTE_UP"
export const LINK_VOTE_DOWN="LINK_VOTE_DOWN"
export const LINK_CREATE="LINK_CREATE"
export const LINK_LOAD="LINK_LOAD"
export const LINK_DELETE="LINK_DELETE"
export const LINK_SORT="LINK_SORT"